name: Release

on:
  push:
    branches:
      - main

jobs:
  build_wheels:
    name: Build wheel
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: astral-sh/setup-uv@v5
        with:
          python-version: '3.10'
      - name: Build wheel
        run: uv build --wheel
      - uses: actions/upload-artifact@v3
        with:
          path: ./dist/*.whl

  build_sdist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: astral-sh/setup-uv@v5
        with:
          python-version: '3.10'
      - name: Build sdist
        run: uv build --sdist
      - uses: actions/upload-artifact@v3
        with:
          path: dist/*.tar.gz

  upload_pypi:
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true

          
      # - name: Publish a Python distribution to PyPI
      #   uses: pypa/gh-action-pypi-publish@v1.12.3
      #   with:
      #     attestations: true

      # - name: Upload Python packages for release notes
      #   uses: softprops/action-gh-release@v0.1.14
      #   with:
      #     files: dist/*
